server:
  port: 8184

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_task?serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      # does not work in this project (hibernate is managed dependently)
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect